import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarTrigger,
} from "@/components/ui/menubar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Menubar>
          <MenubarMenu>
            <MenubarTrigger>Marketing</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="/about">About</Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="/contact">Contact</Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>Blog</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="/blog">List</Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="/blog/topic-name">Topic</Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>Dashboard</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="/dashboard/settings">Settings</Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="/dashboard/profile">Profile</Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
        </Menubar>
        {children}
      </body>
    </html>
  );
}
